title: Setting Up Canon IJ Printer With USB
description: Canon printer setup is very easy process. you just need to visit canon.com/ijsetup and follow on screen instructions to download drivers and setup your printer.
theme: jekyll-theme-cayman
